# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: trust-bundles
description: Nadrama CA trust store bundles created via trust-manager
type: application
version: "1.0.0"
appVersion: "0.18.0"
