# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-cluster
  namespace: system-cluster-api
spec:
  controlPlaneEndpoint:
    host: testcluster.cluster.env
    port: 443
