# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: default-ca-bundle
spec:
  sources:
    - useDefaultCAs: true
  target:
    configMap:
      key: "ca.crt"
    namespaceSelector:
      matchLabels:
        default-ca-bundle: from-trust-bundles
