# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: selfsigned-and-default-ca-bundle
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: "selfsigned-ca-certificate-secret"
        key: "tls.crt"
  target:
    configMap:
      key: "ca.crt"
    namespaceSelector:
      matchLabels:
        selfsigned-and-default-ca-bundle: from-trust-bundles
