# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nadrama-hello-httproute
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: system-traefik
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nadrama-hello-service
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: nadrama-hello-backend-tls-policy
spec:
  targetRefs:
    - group: "" # must be blank
      kind: Service
      name: nadrama-hello-service
  validation:
    hostname: nadrama-hello-service.default.svc.cluster.local
    caCertificateRefs:
      - group: "" # must be blank
        name: selfsigned-ca-bundle
        kind: ConfigMap
