# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-certificate
spec:
  secretName: {{ .Values.name }}-certificate-secret
  dnsNames:
    - {{ .Values.name }}-service
    - {{ .Values.name }}-service.default
    - {{ .Values.name }}-service.default.svc
    - {{ .Values.name }}-service.default.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-clusterissuer
