# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-httproute
spec:
  parentRefs:
    - name: system-traefik-gateway
      namespace: system-traefik
  {{- if .Values.hostname }}
  hostnames:
    - {{ .Values.hostname }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.path }}
      backendRefs:
        - name: {{ .Values.name }}-service
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: {{ .Values.name }}-backend-tls-policy
spec:
  targetRefs:
    - group: "" # must be blank
      kind: Service
      name: {{ .Values.name }}-service
  validation:
    hostname: {{ .Values.name }}-service.default.svc.cluster.local
    caCertificateRefs:
      - group: "" # must be blank
        name: system-selfsigned-ca-bundle
        kind: ConfigMap
