# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: nadrama-hello-service
spec:
  selector:
    app: nadrama-hello
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
