# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: nadrama-hello
description: Nadrama "Hello World" example app chart
type: application
version: "1.0.0"
appVersion: "1.0.0"
