# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: system-argocd-httproute
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: system-traefik
  hostnames:
    - "argocd.{{ .Values.nadrama.ingress.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: system-argocd-server
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: argocd-backend-tls-policy
spec:
  targetRefs:
    - group: "" # must be blank
      kind: Service
      name: system-argocd-server
  validation:
    hostname: system-argocd-server.system-argocd.svc.cluster.local
    caCertificateRefs:
      - group: "" # must be blank
        name: selfsigned-ca-bundle
        kind: ConfigMap
