# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
{{ range $name, $app := index .Values.platform.system.crds }}
{{ if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $name }}-app"
spec:
  project: system
  source:
    repoURL: "https://github.com/nadrama-com/charts.git"
    targetRevision: "main" # 'v1' in prod
    path: "crds/{{ $name }}"
    helm:
      releaseName: "system-{{ $name }}"
      skipCrds: {{ if $name | hasSuffix "-crds" }}false{{ else }}true{{ end }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ $app.namespace }}"
{{ end }}
{{ end }}
