# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
{{ range .Values.apps.system }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .name }}-app"
spec:
  project: system
  source:
    repoURL: "https://github.com/nadrama-com/charts.git"
    targetRevision: "main" # 'production' in prod
    path: "{{ .name }}"
    helm:
      releaseName: "system-{{ .name }}"
      skipCrds: {{ if .name | hasSuffix "-crds" }}false{{ else }}true{{ end }}
      valuesObject:
        nadrama:
{{- toYaml $.Values.nadrama | nindent 10 }}
        argo-cd:
          global:
            domain: {{ index $.Values "argo-cd" "global" "domain" }}
          configs:
            cm:
              create: {{ index $.Values "argo-cd" "configs" "cm" "create" }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .namespace }}"

{{ end }}
