# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
# CertificateRequestPolicy allowing cert manager to establish a CA certificate for self-signed certificates
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: selfsigned-ca-issuer-crp
spec:
  selector:
    issuerRef:
      kind: Issuer
      name: selfsigned-ca-issuer
    namespace:
      matchNames:
        - "system-cert-manager"
  allowed:
    commonName:
      value: "{{ .Values.nadrama.ingress.hostname }}"
      required: true
    isCA: true
    usages:
      - "digital signature"
      - "key encipherment"
      - "cert sign"
      - "crl sign"
    subject:
      organizations: { values: ["*"] }
      countries: { values: ["*"] }
      organizationalUnits: { values: ["*"] }
      localities: { values: ["*"] }
      provinces: { values: ["*"] }
      streetAddresses: { values: ["*"] }
      postalCodes: { values: ["*"] }
      serialNumber: { value: "*" }
