# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
# CertificateRequestPolicy for Traefik ingress on cluster subdomain
# Can be either the ClusterIssuer for self-signed certificates,
# or the Nadrama env-cool Issuer (in traefik chart) for LetsEncrypt certificates.
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: traefik-default-certificate-crp
spec:
  selector:
{{ index .Values.nadrama "cert-manager" "defaultCertificate" "selector" | toYaml | indent 6 }}
  allowed:
    # Deny commonName - must not be present
    # Only allow specific service DNS name patterns
    dnsNames:
      required: true
      validations:
        - rule: self == '{{ index .Values.nadrama "cert-manager" "defaultCertificate" "allowedHostname" }}' || self == '*.{{ index .Values.nadrama "cert-manager" "defaultCertificate" "allowedHostname" }}'
          message: 'DNS names must be {{ index .Values.nadrama "cert-manager" "defaultCertificate" "allowedHostname" }} or *.{{ index .Values.nadrama "cert-manager" "defaultCertificate" "allowedHostname" }}'
    # Restrict to server auth only
    usages:
      - "digital signature"
      - "key encipherment"
      - "server auth"
    # Prevent CA certificates
    isCA: false
    # Allow basic subject fields but not required
    subject:
      organizations: { values: ["*"] }
      countries: { values: ["*"] }
      organizationalUnits: { values: ["*"] }
      localities: { values: ["*"] }
      provinces: { values: ["*"] }
      streetAddresses: { values: ["*"] }
      postalCodes: { values: ["*"] }
      serialNumber: { value: "*" }
