# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: deny-namespace-vap
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*/*"]
  validations:
    # do not apply this policy if...
    - expression: >
        !(
          request.userInfo.groups.exists(g, g.startsWith("nadrama:")) &&
          (
            request.namespace == "" ||
            (
              (request.namespace.startsWith('kube-') || request.namespace.startsWith('system-')) &&
              !(request.kind.kind == "Pod" && request.operation == "DELETE" && request.userInfo.groups.exists(g, g == "nadrama:admins"))
            )
          )
        )
      message: "Access to system-/kube- prefixed namespaces and cluster-wide resources is not permitted. See https://nadrama.com/docs/limits"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: deny-namespace-vapb
spec:
  policyName: deny-namespace-vap
  validationActions: ["Deny", "Audit"]
  matchResources:
    namespaceSelector: {}
