# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
# nadrama:
#   ingress:
#     hostname: (string)

# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argo-cd:
  crds:
    install: false
  global:
    # set via install.sh/render.sh (see var.sh)
    dualStack:
      ipFamilyPolicy: PreferDualStack
      ipFamilies:
        - IPv4
        - IPv6
  dex:
    enabled: false
  redis:
    enabled: true
  redisSecretInit:
    enabled: false # we have disabled helm hooks and do this via ./redis-password.sh instead
  configs:
    params:
      application.namespaces: "system-apps"
    cm:
      application.resourceTrackingMethod: annotation
      # note: both 'admin.enabled' and 'oidc.config' are set in production.
      # however, these are commented out here so you can use argocd-local users.
      admin.enabled: false
      oidc.config: |
        name: Nadrama
        issuer: https://console.nadrama.com
        enablePKCEAuthentication: true
        clientId: acc0000000001r010000000000000
        clientSecret: random-value
        requestedScopes:
          - openid
          - profile
          - email
      users.anonymous.enabled: false
    rbac:
      policy.csv: |
        g, system:masters, role:admin
      policy.default: "role:readonly"
  server:
    certificate:
      enabled: true
      domain: "system-argocd-server.system-argocd"
      additionalHosts:
        - system-argocd-server
        - system-argocd-server.system-argocd.svc
        - system-argocd-server.system-argocd.svc.cluster.local
      issuer:
        kind: ClusterIssuer
        name: selfsigned-clusterissuer
  application-set:
    certificate:
      enabled: true
      domain: "system-argocd-application-set-controller.system-argocd"
      additionalHosts:
        - system-argocd-application-set-controller
        - system-argocd-application-set-controller.system-argocd.svc
        - system-argocd-application-set-controller.system-argocd.svc.cluster.local
      issuer:
        kind: ClusterIssuer
        name: selfsigned-clusterissuer
