# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: system-selfsigned-and-default-ca-bundle
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: "system-selfsigned-ca-certificate-secret"
        key: "tls.crt"
  target:
    configMap:
      key: "ca.crt"
    namespaceSelector:
      matchLabels:
        cluster.nadrama.com/bundles-selfsigned-and-default-ca: from-trust-bundles
