# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
# NadramaMachineTemplate.
# If changing this, also need to update NadramaMachine.
# Reference material:
# https://cluster-api.sigs.k8s.io/developer/providers/contracts/infra-machine
# https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nadramamachinetemplates.infrastructure.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/provider: nadrama
    cluster.x-k8s.io/v1beta1: v1beta1
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
      - cluster-api
    kind: NadramaMachineTemplate
    listKind: NadramaMachineTemplateList
    plural: nadramamachinetemplates
    shortNames:
      - nmt
    singular: nadramamachinetemplate
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          description: NadramaMachineTemplate is the schema for the Nadrama Machine Templates API.
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: NadramaMachineTemplateSpec defines the desired state of NadramaMachineTemplate.
              properties:
                template:
                  description:
                    NadramaMachineTemplateResource describes the data needed
                    to create a cluster node from a template.
                  properties:
                    metadata:
                      description: |-
                        Standard object's metadata.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
                      properties:
                        annotations:
                          additionalProperties:
                            type: string
                          description: |-
                            Annotations is an unstructured key value map stored with a resource that may be
                            set by external tools to store and retrieve arbitrary metadata. They are not
                            queryable and should be preserved when modifying objects.
                            More info: http://kubernetes.io/docs/user-guide/annotations
                          type: object
                        labels:
                          additionalProperties:
                            type: string
                          description: |-
                            Map of string keys and values that can be used to organize and categorize
                            (scope and select) objects. May match selectors of replication controllers
                            and services.
                            More info: http://kubernetes.io/docs/user-guide/labels
                          type: object
                      type: object
                    spec:
                      description:
                        Spec is the specification of the desired behavior
                        of the machine.
                      properties:
                        nodeType:
                          description: "NodeType is the type of node to create.
                            e.g. m4.xlarge on AWS"
                          minLength: 2
                          type: string
                        subnets:
                          description: |-
                            Subnets is a reference to the subnet(s) to use for this instance. If not specified, any cluster subnet may be used.
                          items:
                            description: Subnet is a subnet IPv4 CIDR used to identify a cluster subnet.
                            type: string
                          type: array
                        providerID:
                          description:
                            ProviderID is the unique identifier as specified by the
                            cloud provider.
                          type: string
                        failureDomain:
                          description: |-
                            failureDomain is the failure domain the machine should be created in, as specified by the Machine spec.
                            Must match a key in the FailureDomains map stored on the cluster object.
                            Note that Nadrama will report back the actual failure domain
                            used in the status.failureDomain field per https://cluster-api.sigs.k8s.io/developer/providers/contracts/infra-machine#inframachine-failure-domain
                          type: string
                      required:
                        - nodeType
                      type: object
                  required:
                    - spec
                  type: object
              required:
                - template
              type: object
            status:
              description: NadramaMachineTemplateStatus defines a status for an NadramaMachineTemplate.
              properties:
                capacity:
                  additionalProperties:
                    anyOf:
                      - type: integer
                      - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  description: |-
                    Capacity defines the resource capacity for this machine.
                    This value is used for autoscaling from zero operations as defined in:
                    https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210310-opt-in-autoscaling-from-zero.md
                  type: object
              type: object
          type: object
      served: true
      storage: true
