---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
  name: capi-serving-cert
  namespace: system-cluster-api
spec:
  dnsNames:
    - capi-webhook-service.system-cluster-api.svc
    - capi-webhook-service.system-cluster-api.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capi-selfsigned-issuer
  secretName: capi-webhook-service-cert
  subject:
    organizations:
      - k8s-sig-cluster-lifecycle
