name: Kind E2E Tests

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  kind-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Kind
        uses: helm/kind-action@v1.12.0
        with:
          config: kind.yaml

        # Add tests here

      - name: Delete Kind cluster
        run: kind delete cluster --name nadrama