# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: argocd
description: Nadrama ArgoCD chart
type: application
version: "1.0.0"
appVersion: "3.0.6"
dependencies:
  - name: argo-cd
    version: "v8.1.2"
    repository: "https://argoproj.github.io/argo-helm"
