# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-default-certificate
spec:
  secretName: traefik-default-certificate-secret
  {{- .Values.nadrama.traefik.defaultCertificate | toYaml | nindent 2 }}
