# Copyright 2025 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  defaultCertificate:
    secretName: {{ .Values.nadrama.traefik.defaultCertificateSecret | default "system-traefik-self-signed-certificate-secret" }}
